[workspace]
members = [
    "crates/foundation/keter-reactor",
    "crates/testing/keter-test",
    "crates/testing/keter-test-runner"
]
resolver = "2"

[workspace.dependencies]
keter-test = { path = "crates/testing/keter-test" }
