[package]
name = "keter-reactor"
version = "0.1.0"
edition = "2021"
authors = ["John Nunley <dev@notgull.net>"]

[[test]]
name = "reactor"
path = "tests/reactor.rs"
harness = false

[dependencies]
async-io = "2"

[target.'cfg(target_os = "linux")'.dependencies.rustix]
version = "0.38.28"
default-features = false
features = ["thread", "std", "process"]

[dev-dependencies]
futures-lite = "2.1.0"
macro_rules_attribute = "0.2.0"
